// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/eltrovert/porto/templates/layouts"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"text-center mb-16 animate-on-scroll\"><h1 class=\"text-5xl font-bold mb-8 font-mono\"><span class=\"text-accent\">&gt;_</span> whoami <span class=\"animate-pulse text-accent ml-2\">_</span></h1></div><div class=\"max-w-4xl mx-auto\"><div class=\"card p-8 animate-on-scroll\"><div class=\"mb-6\"><h2 class=\"text-2xl font-bold mb-4 text-accent font-mono\">El Muhammad</h2><p class=\"text-gray-300 text-lg leading-relaxed\">Senior DevOps & Cloud Architect with 13+ years of global experience in building scalable infrastructure, automation systems, and cloud-native solutions. Currently passionate about building a personal cloud infrastructure at home and exploring the intersection of DevOps and machine learning operations.</p></div><div class=\"grid grid-cols-1 md:grid-cols-2 gap-8 mt-8\"><div><h3 class=\"text-lg font-bold text-accent font-mono mb-4\">Expertise</h3><ul class=\"space-y-2 text-gray-400\"><li>• Kubernetes & Cloud-Native Ecosystems</li><li>• MLOps & Distributed Training</li><li>• CI/CD Pipelines & GitOps</li><li>• Cloud Migration & Cost Optimization</li><li>• Infrastructure as Code</li><li>• Observability & Monitoring</li></ul></div><div><h3 class=\"text-lg font-bold text-accent font-mono mb-4\">Currently</h3><ul class=\"space-y-2 text-gray-400\"><li>• Building personal homelab infrastructure</li><li>• Exploring edge computing solutions</li><li>• Contributing to open source projects</li><li>• Writing about DevOps best practices</li></ul></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Page("About", "about").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
