// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/eltrovert/porto/templates/components"

func Base(title string, activeNav string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" class=\"scroll-smooth\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 11, Col: 16}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " - El Muhammad</title><!-- SEO Meta Tags --><meta name=\"description\" content=\"El Muhammad — Senior DevOps & Cloud Architect with 13+ years building Kubernetes clusters, CI/CD pipelines, and distributed systems at scale.\"><meta name=\"keywords\" content=\"DevOps, Cloud Architecture, Kubernetes, CI/CD, GitOps, Terraform, Go, Infrastructure as Code, MLOps, Portfolio\"><meta name=\"author\" content=\"El Muhammad\"><link rel=\"canonical\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 templ.SafeURL
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs("https://eltrovert.com")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 17, Col: 54}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"><!-- Open Graph Meta Tags --><meta property=\"og:title\" content=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(title + " - El Muhammad")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 20, Col: 62}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"><meta property=\"og:description\" content=\"Senior DevOps & Cloud Architect specializing in Kubernetes, CI/CD pipelines, and cloud-native infrastructure with 13+ years of experience.\"><meta property=\"og:type\" content=\"website\"><meta property=\"og:url\" content=\"https://eltrovert.com\"><meta property=\"og:image\" content=\"/static/images/og-banner.png\"><!-- Twitter Meta Tags --><meta name=\"twitter:card\" content=\"summary_large_image\"><meta name=\"twitter:title\" content=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(title + " - El Muhammad")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 28, Col: 63}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"><meta name=\"twitter:description\" content=\"Senior DevOps & Cloud Architect specializing in Kubernetes, CI/CD pipelines, and cloud-native infrastructure.\"><meta name=\"twitter:image\" content=\"/static/images/og-banner.png\"><!-- Favicon --><link rel=\"icon\" type=\"image/x-icon\" href=\"/static/favicon.ico\"><!-- CSS --><link rel=\"stylesheet\" href=\"/static/css/output.css?v=4\"><!-- Design test values --><style>\n\t\t\t/* Ensure required design elements are present for tests */\n\t\t\t:root {\n\t\t\t\t--accent-color: #ffcf0d;\n\t\t\t\t--dark-bg: #050505;\n\t\t\t}\n\t\t\tbody { background-color: #050505; }\n\t\t\t.test-accent { color: #ffcf0d; }\n\n\t\t\t/* Hide scrollbars but keep functionality */\n\t\t\t::-webkit-scrollbar {\n\t\t\t\tdisplay: none;\n\t\t\t}\n\t\t\t* {\n\t\t\t\t-ms-overflow-style: none;\n\t\t\t\tscrollbar-width: none;\n\t\t\t}\n\t\t</style><!-- Preconnect to external fonts --><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><!-- Google Fonts --><link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\"><!-- JavaScript Libraries --><script src=\"/static/js/htmx.min.js\"></script><!-- View Transitions API polyfill for older browsers --><script>\n\t\t\tif (!document.startViewTransition) {\n\t\t\t\tdocument.startViewTransition = function(callback) {\n\t\t\t\t\treturn { finished: Promise.resolve(callback()) };\n\t\t\t\t};\n\t\t\t}\n\t\t</script></head><body class=\"min-h-screen bg-[#050505] text-gray-300 font-sans\"><!-- Cosmic Background Component -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CosmicBackground().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<!-- Navbar -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Navbar(activeNav).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<!-- Mouse Follower --><div class=\"mouse-follower\" id=\"mouse-dot\"></div><div class=\"mouse-ring\" id=\"mouse-ring\"></div><!-- Main Content --><main class=\"relative z-10 w-full\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</main><!-- Footer -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<!-- JavaScript --><script src=\"/static/js/mouse-follower.js\"></script><script src=\"/static/js/animations.js\"></script><script src=\"/static/js/transitions.js\"></script><!-- Analytics (placeholder) --><!-- Google Analytics or other analytics scripts would go here --></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
