// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "strconv"

func TechHighlight() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"pt-24 pb-40 relative z-10 overflow-hidden bg-[#050505]\"><!-- Subtle cosmic haze --><div class=\"absolute inset-0 pointer-events-none\"><div class=\"absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-indigo-600/10 blur-[180px] rounded-full mix-blend-screen opacity-30\"></div><div class=\"absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[300px] h-[300px] bg-accent/5 blur-[120px] rounded-full mix-blend-screen\"></div></div><!-- Inner Container --><div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full relative z-10\"><!-- Header Section: Traversing Unknown Domain --><div class=\"relative text-center mb-32 max-w-4xl mx-auto pt-8\"><div class=\"flex flex-col items-center justify-center relative animate-on-scroll\"><!-- Typography Layering --><h2 class=\"relative z-10 leading-none tracking-tighter font-mono\"><span class=\"block text-6xl md:text-8xl lg:text-9xl font-bold opacity-30 select-none absolute top-0 left-1/2 -translate-x-1/2 -translate-y-12 w-full text-center text-transparent\" style=\"-webkit-text-stroke: 1px rgba(255, 255, 255, 0.5);\">TRAVERSING</span> <span class=\"block text-5xl md:text-7xl lg:text-8xl font-black text-white relative z-20 mt-4\">UNKNOWN DOMAIN</span> <span class=\"block text-xs text-accent uppercase tracking-[0.5em] mt-6 opacity-80\">[ SYSTEM_LOG: INFRASTRUCTURE_EXPLORATION_MODE_ACTIVE ]</span></h2><div class=\"mt-16 max-w-2xl relative border-l-2 border-accent/30 pl-6 text-left\"><div class=\"animate-on-scroll\" style=\"transition-delay: 200ms;\"><p class=\"text-lg md:text-xl text-gray-400 font-mono leading-relaxed\"><span class=\"text-accent\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("//")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/tech_highlight.templ`, Line: 39, Col: 39}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span> I'm sharing how I approach infrastructure challenges and how my DevOps mental model helps me traverse unknown domain knowledge with clarity and structure.</p></div></div></div></div><!-- Cards Grid --><div class=\"grid grid-cols-1 md:grid-cols-3 gap-6 mx-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = PostCard("Infrastructure", "Cluster Constellations", "Navigating the complex galaxy of Kubernetes pods and nodes.", K8sVisual(), 100).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = PostCard("Automation", "Velocity Thrusters", "Building resilient CI/CD pipelines for lightspeed delivery.", PipelineVisual(), 200).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = PostCard("Architecture", "Orbital Mechanics", "Distributed patterns and high-availability system design.", GridVisual(), 300).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func PostCard(category string, title string, subtitle string, visual templ.Component, delayMs int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<a href=\"#\" class=\"group relative bg-[#0a0a0a] border border-white/5 rounded-none overflow-hidden hover:border-accent/30 transition-all duration-500 flex flex-col h-full hover:shadow-[0_0_30px_rgba(255,207,13,0.05)] hover:-translate-y-1 animate-on-scroll\" style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("transition-delay: " + strconv.Itoa(delayMs) + "ms;")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/tech_highlight.templ`, Line: 60, Col: 62}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"><!-- Corner Accents --><div class=\"absolute top-0 left-0 w-2 h-2 border-l border-t border-white/20\"></div><div class=\"absolute top-0 right-0 w-2 h-2 border-r border-t border-white/20\"></div><div class=\"absolute bottom-0 left-0 w-2 h-2 border-l border-b border-white/20\"></div><div class=\"absolute bottom-0 right-0 w-2 h-2 border-r border-b border-white/20\"></div><!-- Visual Container --><div class=\"h-64 bg-[#0f0f0f] flex items-center justify-center relative overflow-hidden border-b border-white/5\"><div class=\"scan-overlay h-[200%] w-full\"></div><div class=\"transform transition-transform duration-500 group-hover:scale-110 relative z-10 grayscale group-hover:grayscale-0 transition-all\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = visual.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></div><!-- Content --><div class=\"p-8 flex-1 flex flex-col justify-end relative z-10 bg-[#0a0a0a]\"><div class=\"mb-3\"><span class=\"text-[10px] font-mono text-accent uppercase tracking-widest border border-accent/20 px-2 py-1 rounded-sm bg-accent/5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(category)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/tech_highlight.templ`, Line: 80, Col: 15}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</span></div><h3 class=\"text-xl font-bold text-white mb-3 group-hover:text-accent transition-colors font-mono\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/tech_highlight.templ`, Line: 83, Col: 108}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</h3><p class=\"text-gray-400 text-sm leading-relaxed font-sans\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(subtitle)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/tech_highlight.templ`, Line: 84, Col: 72}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</p><div class=\"mt-6 flex items-center text-xs font-bold text-gray-500 uppercase tracking-wider group-hover:text-white transition-colors font-mono\"><span>> Initialize Sequence</span> <span class=\"animate-pulse ml-1\">_</span></div></div></a>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func K8sVisual() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var8 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var8 == nil {
			templ_7745c5c3_Var8 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<div class=\"relative transform scale-100\"><!-- Central Node / Planet --><div class=\"w-32 h-32 rounded-full border border-white/10 relative flex items-center justify-center bg-white/5 backdrop-blur-sm shadow-[0_0_15px_rgba(255,255,255,0.02)]\"><div class=\"absolute inset-0 border border-dashed border-white/10 rounded-full animate-spin\" style=\"animation-duration: 10s;\"></div><!-- Orbiting Pods --><div class=\"absolute w-[140%] h-[140%] animate-spin\" style=\"animation-direction: reverse; animation-duration: 8s;\"><div class=\"absolute top-0 left-1/2 -translate-x-1/2 w-4 h-4 bg-accent rounded-full blur-[1px] shadow-[0_0_10px_var(--accent)]\"></div></div><div class=\"grid grid-cols-2 gap-2 relative z-10\"><div class=\"w-6 h-6 rounded bg-white/5 border border-white/10\"></div><div class=\"w-6 h-6 rounded bg-white/5 border border-white/10\"></div><div class=\"w-6 h-6 rounded bg-white/5 border border-white/10\"></div><div class=\"w-6 h-6 rounded bg-accent/10 border border-accent/50\"></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func PipelineVisual() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var9 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var9 == nil {
			templ_7745c5c3_Var9 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<div class=\"flex items-center space-x-2 transform scale-100\"><div class=\"relative\"><div class=\"w-10 h-10 rounded-lg border border-green-500/30 flex items-center justify-center bg-green-500/5 shadow-[0_0_15px_rgba(34,197,94,0.1)]\"><svg class=\"w-5 h-5 text-green-500/80\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"></path> <polyline points=\"3.27,6.96 12,12.01 20.73,6.96\"></polyline> <line x1=\"12\" y1=\"22.08\" x2=\"12\" y2=\"12\"></line></svg></div></div><!-- Stream --><div class=\"w-12 h-1 bg-white/5 relative overflow-hidden rounded-full\"><div class=\"absolute inset-0 bg-accent/80 animate-shimmer\" style=\"animation-duration: 1.5s;\"></div></div><div class=\"w-10 h-10 rounded-lg border border-accent/30 flex items-center justify-center bg-accent/5 shadow-[0_0_15px_rgba(255,207,13,0.1)]\"><svg class=\"w-5 h-5 text-accent\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><line x1=\"6\" y1=\"3\" x2=\"6\" y2=\"15\"></line> <circle cx=\"18\" cy=\"6\" r=\"3\"></circle> <circle cx=\"6\" cy=\"18\" r=\"3\"></circle> <path d=\"M18 9a9 9 0 0 1-9 9\"></path></svg></div><!-- Stream --><div class=\"w-12 h-1 bg-white/5 relative overflow-hidden rounded-full\"><div class=\"absolute inset-0 bg-accent/80 animate-shimmer\" style=\"animation-duration: 1.5s; animation-delay: 75ms;\"></div></div><svg class=\"w-6 h-6 text-white/80 rotate-45\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z\"></path> <path d=\"M12 10a6 6 0 0 0-6-6H4a2 2 0 0 0-2 2v2\"></path> <path d=\"M22 13h-4.5\"></path> <rect x=\"2\" y=\"10\" width=\"20\" height=\"8\" rx=\"2\"></rect></svg></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func GridVisual() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var10 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var10 == nil {
			templ_7745c5c3_Var10 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div class=\"relative w-32 h-32 transform rotate-45 scale-75\"><div class=\"absolute inset-0 grid grid-cols-2 gap-4\"><div class=\"rounded-xl border border-white/10 bg-white/5 backdrop-blur-sm shadow-xl\"></div><div class=\"rounded-xl border border-accent/40 bg-accent/5 backdrop-blur-sm shadow-[0_0_20px_rgba(255,207,13,0.1)] animate-pulse\"></div><div class=\"rounded-xl border border-white/10 bg-white/5 backdrop-blur-sm shadow-xl\"></div><div class=\"rounded-xl border border-white/10 bg-white/5 backdrop-blur-sm shadow-xl\"></div></div><!-- Connection Lines --><div class=\"absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-2 h-2 bg-white rounded-full z-20 shadow-[0_0_10px_white]\"></div><div class=\"absolute inset-0 border border-white/5 rounded-full scale-150\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
